import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#79542e",
        "primary-container": "#956c44",
        surface: "#fbf9f4",
        "surface-container-low": "#f5f3ee",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e4e2dd",
        "surface-container-high": "#eae8e3",
        "surface-container": "#f0eee9",
        "surface-variant": "#e4e2dd",
        "surface-bright": "#fbf9f4",
        "surface-dim": "#dbdad5",
        "on-surface": "#1b1c19",
        "on-surface-variant": "#524439",
        secondary: "#5f5e5e",
        "secondary-container": "#e4e2e1",
        "on-primary": "#ffffff",
        "on-primary-container": "#fffbff",
        "outline-variant": "#d8c3b4",
        outline: "#857467",
        tertiary: "#665a4a",
        "tertiary-container": "#807262",
        "tertiary-fixed": "#f1e0cc",
        "tertiary-fixed-dim": "#d5c4b1",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fffbff",
        "on-background": "#1b1c19",
        background: "#fbf9f4",
        "inverse-surface": "#30312e",
        "inverse-on-surface": "#f2f1ec",
        "inverse-primary": "#eebd8e",
        "surface-tint": "#7c5730",
        "primary-fixed": "#ffdcbd",
        "primary-fixed-dim": "#eebd8e",
        "secondary-fixed": "#e4e2e1",
        "secondary-fixed-dim": "#c8c6c6",
        "on-primary-fixed": "#2c1600",
        "on-primary-fixed-variant": "#61401b",
        "on-secondary-fixed": "#1b1c1c",
        "on-secondary-fixed-variant": "#474747",
        "on-secondary-container": "#656464",
        "on-tertiary-fixed": "#231a0e",
        "on-tertiary-fixed-variant": "#504536",
      },
      fontFamily: {
        headline: ["var(--font-manrope)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        label: ["var(--font-inter)", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};

export default config;
